version: "2"

services:
  app:
    image: golang:1.12-alpine
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: sleep 7200 
    